### ISSUE TITLE
async error: bad base64 decode

### ISSUE THREAD

**Issue by roycewilliams** [ryancdotorg/dkimscan#1]
$ ./dkimscan.pl alpca.org

fqdn: default._domainkey.alpca.org

txt:  "v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA19OAUXQIu+Dk+6SWW1QACXUKHbn/Tmb27JeuQeM5kQ6WoUu9VdObRej7AR2AEFDaMwt9vgjKqqxf3Ag7sU2lGJOiNYRlJPLWLFxhD/WQ9pUURJ/clJODZNiZdXOM9cf1zrc5A9XjHKQ8hQNtzpgp0ymAvMZA01FVOBPt9OQxJ7ZLv3bQqxuNPYIvcQuPllsaI"
        "gmtw2OjQDlL7ZbgC61Gq1LI+X2fFJ5aKvMJ/gaDL8bmB/VqidGvSNYeqvFZ8v2Am+fGZpgRpjytBsxOEt04hUam+xOS4BNvHYgq+SCG5l75cPs/GfXAwfo1B6fJ3g8G3o1iWWGzmbi7+2XFh+p2YwIDAQAB;"

key:  MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA19OAUXQIu+Dk+6SWW1QACXUKHbn/Tmb27JeuQeM5kQ6WoUu9VdObRej7AR2AEFDaMwt9vgjKqqxf3Ag7sU2lGJOiNYRlJPLWLFxhD/WQ9pUURJ/clJODZNiZdXOM9cf1zrc5A9XjHKQ8hQNtzpgp0ymAvMZA01FVOBPt9OQxJ7ZLv3bQqxuNPYIvcQuPllsaI===

Async died within Net::DNS::Async: RSA.xs:198: OpenSSL error: bad base64 decode at blib/lib/Crypt/OpenSSL/RSA.pm (autosplit into blib/lib/auto/Crypt/OpenSSL/RSA/new_public_key.al) line 88, <DATA> line 12.

**Comment by ryancdotorg** [comment]
Well, that was fast, lol.

This actually works fine on my machine, but it looks like for some reason the parser cut off the end of the key for you. Something is going wrong in the `parse_dkim_text` function, are you able to debug at all?

**Comment by ryancdotorg** [comment]
Does it work if you change `$txt =~ s/\"\s+\"/ /g;` to `$txt =~ s/\"//g;`?

**Comment by roycewilliams** [comment]
Same result. (And note that this is Perl v5.26.2 on FreeBSD, so if the error proves elusive, it's up to you how much effort to spend on it. :))

**Comment by ryancdotorg** [comment]
Do you have a Linux box you can try it on?

On your console, do you see backslashes before the semicolons?

**Comment by roycewilliams** [comment]
Hmm ... same result on Ubuntu 16.04 / Linux 4.4.0-138-generic
There is a backslash before the final semicolon ([...]`AQAB\;`)

**Comment by ryancdotorg** [comment]
Am able to repro on Ubuntu 16.04, give me a bit.

**Comment by ryancdotorg** [comment]
okay, i think i fixed it, please try again

**Comment by roycewilliams** [comment]
Confirmed fixed on both of my test systems. Thanks!
